redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  volumes:
    - ./app:/app
  ports:
    - 3000:3000
  environment:
    - NODE_ENV=development
    - PORT=3000
    - REDIS_URL=redis://cache
  command:
    sh -c 'npm i --save redis'
    sh -c 'npm i --save express'
    sh -c 'npm i && node server.js'
  links:
    - redis

redis-commander:
  container_name: redis-commander
  hostname: redis-commander
  image: rediscommander/redis-commander:latest
  restart: always
  environment:
    - REDIS_HOSTS=local:redis:6379
  ports:
    - "8081:8081"
  links:
    - redis